### ISSUE TITLE
issues when run cmake ../src on path /realsr-ncnn-vulkan/build 

### ISSUE THREAD

**Issue by SokPhanith** [Qengineering/realsr-ncnn-Jetson-Nano#1]
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.20/Modules/FindVulkan.cmake:99 (find_package_handle_standard_args)
  CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/phanith/realsr-ncnn-vulkan/build/CMakeFiles/CMakeOutput.log".
See also "/home/phanith/realsr-ncnn-vulkan/build/CMakeFiles/CMakeError.log".

**Comment by Qengineering** [comment]
The error is caused by the missing vulkan.h header normally found in `/usr/include/vulkan/`.
On my Nano it was already available, but thanks to you I now know it's missing on a fresh OS. 

Please install the missing files with 
```
sudo apt-get install libvulkan-dev
```

Next, clean your build directory and start all over again.
``` 
cd realsr-ncnn-vulkan
sudo rm -rf build
mkdir build
cd build
cmake ../src
```

**Comment by SokPhanith** [comment]
Thank you so much it's working now.
