### ISSUE TITLE
Request for deblurring application

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/realsr-ncnn-Jetson-Nano#3]
Dear Sir,

By any chance can you develop a fast and lightweight image de blurring application ?
Just a polite request.

**Comment by Qengineering** [comment]
That's not so easy to do either.
The most common way is to use an FFT kernel that describes the desired blur.
You need one 2D forward FFT, a convolution phase and a backward FFT.
FFTs are usually 2^x sizes (32,64,128 etc.). Other formats requires additional algorithms. As you can imagine, a lightweight solution is not easy to find. Often, the results are also disappointing. Only very well defined blur can be reasonable eliminated.

**Comment by rsingh2083** [comment]
Thanks for the suggestions sir
